"""
backtester.py
─────────────
Backtester class for Phase 5.

Simulates the regime-aware portfolio strategy over historical data using vectorbt.
Applies continuous weight targets and configurable transaction costs to calculate
accurate performance metrics, and plots the equity curve against a benchmark.
"""

import logging
from typing import Dict, Optional, Tuple

import pandas as pd
import numpy as np
import vectorbt as vbt

from src.config import TRANSACTION_COST, BENCHMARK_TICKERS

logger = logging.getLogger(__name__)

class Backtester:
    """
    Simulates portfolio performance from targeted weights using vectorbt.
    Compare the dynamic regime strategy against a buy-and-hold benchmark.
    """

    def __init__(self, transaction_cost: float = TRANSACTION_COST):
        """
        Initialize the backtester.
        
        Parameters
        ----------
        transaction_cost : float
            Proportional cost per trade (e.g., 0.001 is 0.1%).
        """
        self.transaction_cost = transaction_cost
        
        # Will hold vectorbt Portfolio objects after running
        self.strategy_portfolio: Optional[vbt.Portfolio] = None
        self.benchmark_portfolio: Optional[vbt.Portfolio] = None
        
        logger.debug(f"Backtester initialized with transaction_cost={self.transaction_cost*100}%")

    def run_backtest(self, prices: pd.DataFrame, target_weights: pd.DataFrame) -> vbt.Portfolio:
        """
        Run the backtest using optimized target weights.
        
        Parameters
        ----------
        prices : pd.DataFrame
            Historical prices for the assets.
        target_weights : pd.DataFrame
            Target weights generated by PortfolioOptimizer. Must be perfectly aligned 
            with `prices` index and columns.
            
        Returns
        -------
        vbt.Portfolio
            The generated vectorbt portfolio object.
        """
        logger.info(f"Running strategy backtest over {len(prices)} trading days...")
        
        # Ensure indexes align
        common_idx = prices.index.intersection(target_weights.index)
        prices_aligned = prices.loc[common_idx]
        weights_aligned = target_weights.loc[common_idx]
        
        # We process target weights over the full assets via vbt.Portfolio.from_orders
        # using the 'target_weights' capability (introduced heavily in vbt 0.2X for allocation tracking)
        # We explicitly set cash_sharing=True so capital is properly rotated.
        
        try:
            pf = vbt.Portfolio.from_orders(
                close=prices_aligned,
                size=weights_aligned,
                size_type='targetpercent',
                call_seq='auto',
                fees=self.transaction_cost,
                freq='1d',                   # daily
                cash_sharing=True,          # sell A to buy B
                group_by=True               # group all columns into 1 portfolio
            )
            self.strategy_portfolio = pf
            logger.info("Strategy backtest complete.")
            return pf
        except Exception as e:
            logger.error(f"Failed to run backtest: {e}")
            raise e

    def run_benchmark(self, prices: pd.DataFrame, benchmark_tickers: list[str] = None) -> vbt.Portfolio:
        """
        Run a simple buy-and-hold benchmark backtest.
        
        Parameters
        ----------
        prices : pd.DataFrame
            Historical prices.
        benchmark_tickers : list[str]
            Tickers to include in the benchmark (equal weight). Defaults to SPY.
            
        Returns
        -------
        vbt.Portfolio
            The generated vectorbt portfolio object representing the benchmark.
        """
        logger.info("Running benchmark backtest...")
        
        if benchmark_tickers is None:
            benchmark_tickers = BENCHMARK_TICKERS
            
        valid_benchmarks = [t for t in benchmark_tickers if t in prices.columns]
        if not valid_benchmarks:
            # Fallback if SPY is missing (unlikely, but safe)
            valid_benchmarks = [prices.columns[0]]
            
        # Extract benchmark prices
        bench_prices = prices[valid_benchmarks]
        
        # Weights are uniform
        n = len(valid_benchmarks)
        weights = pd.DataFrame(1.0/n, index=prices.index, columns=bench_prices.columns)
        
        try:
            pf_bench = vbt.Portfolio.from_orders(
                close=bench_prices,
                size=weights,
                size_type='targetpercent',
                call_seq='auto',
                fees=self.transaction_cost,
                freq='1d',
                cash_sharing=True,
                group_by=True
            )
            self.benchmark_portfolio = pf_bench
            logger.info("Benchmark backtest complete.")
            return pf_bench
        except Exception as e:
            logger.error(f"Failed to run benchmark: {e}")
            raise e

    def get_metrics(self) -> pd.DataFrame:
        """
        Extract KPIs for both strategy and benchmark after running.
        
        Returns
        -------
        pd.DataFrame
            DataFrame comparing Strategy vs Benchmark on key metrics.
        """
        if self.strategy_portfolio is None:
            raise ValueError("Must run_backtest() first.")
            
        metrics = ["Total Return [%]", "Return (Ann.) [%]", "Volatility (Ann.) [%]", 
                   "Max Drawdown [%]", "Sharpe Ratio", "Sortino Ratio", "Calmar Ratio"]
                   
        s_stats = self.strategy_portfolio.stats()
        
        res = {}
        # Safely extract metrics
        for m in metrics:
            if m in s_stats.index:
                res[m] = {"Strategy": s_stats[m]}
            else:
                res[m] = {"Strategy": np.nan}
                
        if self.benchmark_portfolio is not None:
            b_stats = self.benchmark_portfolio.stats()
            for m in metrics:
                if m in b_stats.index:
                    res[m]["Benchmark"] = b_stats[m]
                else:
                    res[m]["Benchmark"] = np.nan
                    
        return pd.DataFrame.from_dict(res, orient='index')

    def plot_equity_curve(self, show: bool = True):
        """
        Plot the strategy equity curve versus the benchmark.
        
        Requires plotly.
        """
        if self.strategy_portfolio is None or self.benchmark_portfolio is None:
            logger.warning("Need both strategy and benchmark to plot comparison.")
            return None
            
        fig = self.strategy_portfolio.value().vbt.plot(trace_kwargs=dict(name="Regime Strategy", line=dict(color="#16a34a", width=2)))
        self.benchmark_portfolio.value().vbt.plot(trace_kwargs=dict(name="Benchmark", line=dict(color="#64748b", dash='dash')), fig=fig)
        
        fig.update_layout(
            title="Portfolio Equity Curve: Regime-Aware vs Buy & Hold Benchmark",
            yaxis_title="Portfolio Value ($)",
            xaxis_title="Date",
            legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01),
            template="plotly_white",
            hovermode="x unified"
        )
        
        if show:
            fig.show()
            
        return fig
